repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        exclude: |
          (?x)^(
            website/.*
          )$
        types_or: [python, pyi]
        require_serial: true

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        exclude: |
          (?x)^(
            website/.*
          )$
        types_or: [ python, pyi ]
        require_serial: true

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        exclude: |
          (?x)^(
            misp_modules/lib/.*|
            tests/.*|
            website/.*
          )$
        types_or: [ python, pyi ]
        require_serial: true
