"""empty message

Revision ID: 183bf8fa2b87
Revises: 91f830996ff4
Create Date: 2024-02-09 15:21:17.274707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '183bf8fa2b87'
down_revision = '91f830996ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('module', schema=None) as batch_op:
            batch_op.add_column(sa.Column('input_attr', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'input_attr' already exist in 'module'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('input_attr')

    # ### end Alembic commands ###
