"""empty message

Revision ID: d6f8bfc9d454
Revises: c0e243696052
Create Date: 2024-02-08 15:23:46.714541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'd6f8bfc9d454'
down_revision = 'c0e243696052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('session_db', schema=None) as batch_op:
            batch_op.add_column(sa.Column('modules_list', sa.String(), nullable=True))
    except OperationalError:
        print("Column 'modules_list' already exist in 'session_db'")

    try:
        with op.batch_alter_table('session_db', schema=None) as batch_op:
            batch_op.drop_column('glob_query')
    except OperationalError:
        print("Column 'glob_query' already dropped from 'session_db'")
    except KeyError:
        print("Column 'glob_query' already dropped from 'session_db'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glob_query', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('modules_list')

    # ### end Alembic commands ###
